### ISSUE TITLE
js error on document show view

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#345] opened 2021-01-25 20:40 UTC
On this document (at least): 

https://studio.covecollective.org/anthologies/engl-262-romanticism-to-resistance/documents/the-little-black-boy-the-chimney-sweeper-soi-holy-thursdaysoi-the-chimney-sweeper-soe-holy-thursday-soelondon

Upon scroll (and only apparently on first load), there's a js error which is thrown. Possibly related to the unbounce on the viewport filter?

<img width="1920" alt="Screen Shot 2021-01-25 at 15 36 03" src="https://user-images.githubusercontent.com/882377/105762929-15d97900-5f23-11eb-98c9-166907d689e9.png">

Here's the reference from console log in chrome:

https://www.chromestatus.com/features/6662647093133312

**Comment by sarastanton** [comment] 2021-03-22 19:33
Unable to reproduce - appears to be fixed now

**Closed by sarastanton** 2021-03-22 19:33 UTC
