### ISSUE TITLE
Purdue tenant js error; Annotation Categories?

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#343] opened 2021-01-18 21:49 UTC
On: https://purdue.covecollective.org/documents/a-far-cry-from-africa-68e20e15-e489-421b-a91d-e9b73290df8e

Upon load, open the js console, and you'll see this error, which appears to be a problem with Annotation Categories. Those can be configured here: https://purdue.covecollective.org/admin/annotation_categories.

```sh
Uncaught TypeError: Cannot read property 'css_classes' of undefined
    at Number.<anonymous> (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:76494)
    at Function.each (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:658)
    at Object.<anonymous> (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:76492)
    at Function.each (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:658)
    at Categories.Annotator.Plugin.Categories.Categories.loadCategories (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:76489)
    at HTMLDivElement.<anonymous> (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:77110)
    at HTMLDivElement.o (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:76195)
    at HTMLDivElement.dispatch (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:5108)
    at HTMLDivElement.elemData.handle (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:4779)
    at Object.trigger (application-697a4bfad51efeed3c6ba24e2cc65fc90c0d245e8efdd9ab30f1d56e66b8da4c.js:5020)
```

![far-cry](https://user-images.githubusercontent.com/882377/104965587-000d0680-59ad-11eb-8497-af3688e40806.png)

**Comment by sarastanton** [comment] 2021-03-22 18:58
Unable to reproduce - appears to be fixed now

**Closed by sarastanton** 2021-03-22 18:58 UTC
Labels: wontfix
